### ISSUE TITLE
Answer and retweet with a push instead of button

### ISSUE THREAD

**Issue by Morpog** [veskuh/Tweetian#55]
Just like accept in many apps.

**Comment by veskuh** [comment]
We tried this already and reverted to old behavior. 

The problem is to implement this in a way that behaves sanely when uploading image or tweeting fails. In current solution page is only popped after the action has been success or fail so user will not lose any data.

I'm not against this as such, but we need to come up with implementation and behavior that will not lose data and will behave well.

**Comment by ghost** [comment]
Dunno if this works since not sure if Dialog are allowed as pageAttached but what if:

new tweet => pushAttached()

and when user tap accept or navigates forward postTweet and set newtweetpage as "busy"

and when tweet succes just popPage or if fail pageStack.forward show error message in newtweetpage...

**Comment by veskuh** [comment]
We now have good solution to this. Thanks to @mike7b4
